
package cellphoneguiapp.njc;


import cellphoneguiapp.njc.utils.Helper;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 * 
 * @author Neil Jason Canete
 */

public class HomePanel extends javax.swing.JPanel {
  private final ImageIcon bg = new ImageIcon(Helper.getImage("homescreen.jpg"));
  private final Image bg_image = Helper.iconToImage(bg).getScaledInstance((int)(420*((float)bg.getIconHeight()/bg.getIconWidth())), 750, Image.SCALE_SMOOTH);
  private final ImageIcon bg_overlay = new ImageIcon(Helper.getImage("lockoverlay.png"));
  private final Image bg_overlay_image = Helper.iconToImage(bg_overlay).getScaledInstance(420, 750, Image.SCALE_SMOOTH);
  
  private final AndroidGUI android_parent;

  private final AndroidAppCollection apps;

  /**
   * Creates new form HomePanel
   * @param androidparent
   */
  public HomePanel(AndroidGUI androidparent) {
    android_parent = androidparent;
    initComponents();
    Timer time = new Timer(0, null);
    time.setDelay(500);
    time.addActionListener(new ActionListener() {
      private boolean withColon;
      private int batteryConsumption = 0;
      private int counter = 0;

      @Override
      public void actionPerformed(ActionEvent e) {
        withColon = !withColon;
        topTime.setText(Helper.getClock12H(withColon));
        homeTime.setText(Helper.getClock24H());
        displayName.setText(android_parent.getDisplayOwnerName());
        counter++;
        if (counter % (60 * 2) == 0) {
          batteryConsumption++;
          topBattery.setText((100 - batteryConsumption) + "%");
        }
      }
    });
    time.start();
    
    apps = new AndroidAppCollection(this);
    try {
      apps.addApp("Call");
      apps.addApp("Messages");
      apps.addApp("Contacts");
      apps.addApp("Facebook");
      apps.addApp("Gallery");
      apps.addApp("Camera");
    } catch (AndroidAppError error) {
      System.err.println(error.getMessage());
    }
      
  }
  
  public AndroidGUI getAndroidParent() {
    return android_parent;
  }
  
  public AndroidAppCollection getApps() {
    return apps;
  }
  
  @Override
  protected void paintComponent(Graphics g) {
    super.paintComponent(g);
    int w = (int)(420*((float)(bg.getIconHeight()/bg.getIconWidth())));
    int h = 750;
    g.drawImage(bg_image, (420/3)-((int)(w/2)),(750/2)-((int)(h/2)),this);
    g.drawImage(bg_overlay_image, 0, 0, this);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    final javax.swing.JPanel topPanel = new javax.swing.JPanel();
    final javax.swing.JLabel topSignal = new javax.swing.JLabel();
    final javax.swing.JLabel topWifi = new javax.swing.JLabel();
    javax.swing.JLabel homeGoogle = new javax.swing.JLabel();
    final javax.swing.JPanel appsPanel = new javax.swing.JPanel();
    final javax.swing.JButton messagesApp = new javax.swing.JButton();
    final javax.swing.JButton callApp = new javax.swing.JButton();
    final javax.swing.JButton contactsApp = new javax.swing.JButton();
    final javax.swing.JButton facebookApp = new javax.swing.JButton();
    final javax.swing.JButton galleryApp = new javax.swing.JButton();
    final javax.swing.JButton cameraApp = new javax.swing.JButton();
    javax.swing.JPanel bottomAppsPanel = new javax.swing.JPanel();
    final javax.swing.JButton bottomCallApp = new javax.swing.JButton();
    final javax.swing.JButton bottomCameraApp = new javax.swing.JButton();
    final javax.swing.JButton bottomMessagesApp = new javax.swing.JButton();
    final javax.swing.JPanel operationPanel = new javax.swing.JPanel();
    final javax.swing.JButton shutdownBtn = new javax.swing.JButton();
    final javax.swing.JButton backBtn = new javax.swing.JButton();
    final javax.swing.JButton homeBtn = new javax.swing.JButton();

    setBackground(new java.awt.Color(0, 0, 0));
    setPreferredSize(new java.awt.Dimension(420, 750));

    topPanel.setBackground(new java.awt.Color(0, 153, 51));
    topPanel.setMaximumSize(new java.awt.Dimension(420, 32767));
    topPanel.setMinimumSize(new java.awt.Dimension(420, 0));
    topPanel.setOpaque(false);
    topPanel.setPreferredSize(new java.awt.Dimension(420, 24));

    topTime.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
    topTime.setForeground(new java.awt.Color(255, 255, 255));
    topTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    topTime.setText("00:00 AM");

    topSignal.setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
    topSignal.setForeground(new java.awt.Color(255, 255, 255));
    topSignal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cellphoneguiapp/njc/resources/topSignal.png"))); // NOI18N
    topSignal.setToolTipText("");
    topSignal.setIconTextGap(0);

    topBattery.setFont(new java.awt.Font("Comic Sans MS", 1, 8)); // NOI18N
    topBattery.setForeground(new java.awt.Color(255, 255, 255));
    topBattery.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cellphoneguiapp/njc/resources/topBattery.png"))); // NOI18N
    topBattery.setText("100%");
    topBattery.setActionCommand("");
    topBattery.setBorderPainted(false);
    topBattery.setContentAreaFilled(false);
    topBattery.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    topBattery.setDefaultCapable(false);
    topBattery.setFocusPainted(false);
    topBattery.setFocusable(false);
    topBattery.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    topBattery.setIconTextGap(0);
    topBattery.setMargin(new java.awt.Insets(0, 0, 0, 0));
    topBattery.setRequestFocusEnabled(false);
    topBattery.setVerifyInputWhenFocusTarget(false);

    topWifi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cellphoneguiapp/njc/resources/topWifi.png"))); // NOI18N

    javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
    topPanel.setLayout(topPanelLayout);
    topPanelLayout.setHorizontalGroup(
      topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(topPanelLayout.createSequentialGroup()
        .addGap(21, 21, 21)
        .addComponent(topTime, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
        .addComponent(topWifi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(topSignal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(2, 2, 2)
        .addComponent(topBattery, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(34, 34, 34))
    );
    topPanelLayout.setVerticalGroup(
      topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
        .addGap(0, 4, Short.MAX_VALUE)
        .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(topTime, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(topWifi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(topBattery, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(topSignal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
    );

    topTime.getAccessibleContext().setAccessibleName("topTime");
    topSignal.getAccessibleContext().setAccessibleName("topSignal");
    topBattery.getAccessibleContext().setAccessibleName("topBattery");
    topWifi.getAccessibleContext().setAccessibleName("topWifi");

    homeGoogle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    homeGoogle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cellphoneguiapp/njc/resources/googleSearch.png"))); // NOI18N
    homeGoogle.setToolTipText("");

    appsPanel.setBackground(new java.awt.Color(255, 153, 51));
    appsPanel.setOpaque(false);

    messagesApp.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
    messagesApp.setForeground(new java.awt.Color(255, 255, 255));
    messagesApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cellphoneguiapp/njc/resources/Messages.png"))); // NOI18N
    messagesApp.setBorderPainted(false);
    messagesApp.setContentAreaFilled(false);
    messagesApp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    messagesApp.setFocusPainted(false);
    messagesApp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    messagesApp.setIconTextGap(0);
    messagesApp.setLabel("Messages");
    messagesApp.setMargin(new java.awt.Insets(0, 8, 0, 8));
    messagesApp.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/cellphoneguiapp/njc/resources/MessagesClicked.png"))); // NOI18N
    messagesApp.setVerticalAlignment(javax.swing.SwingConstants.TOP);
    messagesApp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    messagesApp.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        appActionPerformed(evt);
      }
    });

    callApp.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
    callApp.setForeground(new java.awt.Color(255, 255, 255));
    callApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cellphoneguiapp/njc/resources/Call.png"))); // NOI18N
    callApp.setText("Call");
    callApp.setBorderPainted(false);
    callApp.setContentAreaFilled(false);
    callApp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    callApp.setFocusPainted(false);
    callApp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    callApp.setIconTextGap(0);
    callApp.setMargin(new java.awt.Insets(0, 8, 0, 8));
    callApp.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/cellphoneguiapp/njc/resources/CallClicked.png"))); // NOI18N
    callApp.setVerticalAlignment(javax.swing.SwingConstants.TOP);
    callApp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    callApp.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        appActionPerformed(evt);
      }
    });

    contactsApp.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
    contactsApp.setForeground(new java.awt.Color(255, 255, 255));
    contactsApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cellphoneguiapp/njc/resources/Contacts.png"))); // NOI18N
    contactsApp.setToolTipText("");
    contactsApp.setBorderPainted(false);
    contactsApp.setContentAreaFilled(false);
    contactsApp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    contactsApp.setFocusPainted(false);
    contactsApp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    contactsApp.setIconTextGap(0);
    contactsApp.setLabel("Contacts");
    contactsApp.setMargin(new java.awt.Insets(0, 8, 0, 8));
    contactsApp.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/cellphoneguiapp/njc/resources/ContactsClicked.png"))); // NOI18N
    contactsApp.setVerticalAlignment(javax.swing.SwingConstants.TOP);
    contactsApp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    contactsApp.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        appActionPerformed(evt);
      }
    });

    facebookApp.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
    facebookApp.setForeground(new java.awt.Color(255, 255, 255));
    facebookApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cellphoneguiapp/njc/resources/Facebook.png"))); // NOI18N
    facebookApp.setBorderPainted(false);
    facebookApp.setContentAreaFilled(false);
    facebookApp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    facebookApp.setFocusPainted(false);
    facebookApp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    facebookApp.setIconTextGap(0);
    facebookApp.setLabel("Facebook");
    facebookApp.setMargin(new java.awt.Insets(0, 8, 0, 8));
    facebookApp.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/cellphoneguiapp/njc/resources/FacebookClicked.png"))); // NOI18N
    facebookApp.setVerticalAlignment(javax.swing.SwingConstants.TOP);
    facebookApp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    facebookApp.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        appActionPerformed(evt);
      }
    });

    galleryApp.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
    galleryApp.setForeground(new java.awt.Color(255, 255, 255));
    galleryApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cellphoneguiapp/njc/resources/Gallery.png"))); // NOI18N
    galleryApp.setBorderPainted(false);
    galleryApp.setContentAreaFilled(false);
    galleryApp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    galleryApp.setFocusPainted(false);
    galleryApp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    galleryApp.setIconTextGap(0);
    galleryApp.setLabel("Gallery");
    galleryApp.setMargin(new java.awt.Insets(0, 8, 0, 8));
    galleryApp.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/cellphoneguiapp/njc/resources/GalleryClicked.png"))); // NOI18N
    galleryApp.setVerticalAlignment(javax.swing.SwingConstants.TOP);
    galleryApp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    galleryApp.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        appActionPerformed(evt);
      }
    });

    cameraApp.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
    cameraApp.setForeground(new java.awt.Color(255, 255, 255));
    cameraApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cellphoneguiapp/njc/resources/Camera.png"))); // NOI18N
    cameraApp.setBorderPainted(false);
    cameraApp.setContentAreaFilled(false);
    cameraApp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    cameraApp.setFocusPainted(false);
    cameraApp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    cameraApp.setIconTextGap(0);
    cameraApp.setLabel("Camera");
    cameraApp.setMargin(new java.awt.Insets(0, 8, 0, 8));
    cameraApp.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/cellphoneguiapp/njc/resources/CameraClicked.png"))); // NOI18N
    cameraApp.setVerticalAlignment(javax.swing.SwingConstants.TOP);
    cameraApp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    cameraApp.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        appActionPerformed(evt);
      }
    });

    bottomAppsPanel.setBackground(new java.awt.Color(255, 153, 102));
    bottomAppsPanel.setOpaque(false);

    bottomCallApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cellphoneguiapp/njc/resources/Call.png"))); // NOI18N
    bottomCallApp.setActionCommand("Call");
    bottomCallApp.setBorderPainted(false);
    bottomCallApp.setContentAreaFilled(false);
    bottomCallApp.setFocusPainted(false);
    bottomCallApp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    bottomCallApp.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/cellphoneguiapp/njc/resources/CallClicked.png"))); // NOI18N
    bottomCallApp.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        appActionPerformed(evt);
      }
    });

    bottomCameraApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cellphoneguiapp/njc/resources/Camera.png"))); // NOI18N
    bottomCameraApp.setActionCommand("Camera");
    bottomCameraApp.setBorderPainted(false);
    bottomCameraApp.setContentAreaFilled(false);
    bottomCameraApp.setFocusPainted(false);
    bottomCameraApp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    bottomCameraApp.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/cellphoneguiapp/njc/resources/CameraClicked.png"))); // NOI18N
    bottomCameraApp.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        appActionPerformed(evt);
      }
    });

    bottomMessagesApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cellphoneguiapp/njc/resources/Messages.png"))); // NOI18N
    bottomMessagesApp.setActionCommand("Messages");
    bottomMessagesApp.setBorderPainted(false);
    bottomMessagesApp.setContentAreaFilled(false);
    bottomMessagesApp.setFocusPainted(false);
    bottomMessagesApp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    bottomMessagesApp.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/cellphoneguiapp/njc/resources/MessagesClicked.png"))); // NOI18N
    bottomMessagesApp.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        appActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout bottomAppsPanelLayout = new javax.swing.GroupLayout(bottomAppsPanel);
    bottomAppsPanel.setLayout(bottomAppsPanelLayout);
    bottomAppsPanelLayout.setHorizontalGroup(
      bottomAppsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(bottomAppsPanelLayout.createSequentialGroup()
        .addGap(26, 26, 26)
        .addComponent(bottomCallApp, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(30, 30, 30)
        .addComponent(bottomMessagesApp, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(28, 28, 28)
        .addComponent(bottomCameraApp, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(36, Short.MAX_VALUE))
    );
    bottomAppsPanelLayout.setVerticalGroup(
      bottomAppsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(bottomAppsPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(bottomAppsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(bottomCallApp, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(bottomCameraApp, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(bottomMessagesApp, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap())
    );

    operationPanel.setBackground(new java.awt.Color(51, 0, 204));
    operationPanel.setOpaque(false);

    shutdownBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cellphoneguiapp/njc/resources/optsBtn.png"))); // NOI18N
    shutdownBtn.setBorderPainted(false);
    shutdownBtn.setContentAreaFilled(false);
    shutdownBtn.setFocusPainted(false);
    shutdownBtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/cellphoneguiapp/njc/resources/optsBtnClicked.png"))); // NOI18N
    shutdownBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        shutdownBtnActionPerformed(evt);
      }
    });

    backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cellphoneguiapp/njc/resources/backBtn.png"))); // NOI18N
    backBtn.setBorderPainted(false);
    backBtn.setContentAreaFilled(false);
    backBtn.setFocusPainted(false);
    backBtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/cellphoneguiapp/njc/resources/backBtnClicked.png"))); // NOI18N
    backBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        backBtnActionPerformed(evt);
      }
    });

    homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cellphoneguiapp/njc/resources/homeBtn.png"))); // NOI18N
    homeBtn.setBorderPainted(false);
    homeBtn.setContentAreaFilled(false);
    homeBtn.setFocusPainted(false);
    homeBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    homeBtn.setIconTextGap(0);
    homeBtn.setName(""); // NOI18N
    homeBtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/cellphoneguiapp/njc/resources/homeBtnClicked.png"))); // NOI18N
    homeBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        homeBtnActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout operationPanelLayout = new javax.swing.GroupLayout(operationPanel);
    operationPanel.setLayout(operationPanelLayout);
    operationPanelLayout.setHorizontalGroup(
      operationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(operationPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(shutdownBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(62, Short.MAX_VALUE))
    );
    operationPanelLayout.setVerticalGroup(
      operationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
      .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
      .addComponent(shutdownBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    shutdownBtn.getAccessibleContext().setAccessibleName("shutdownBtn");
    backBtn.getAccessibleContext().setAccessibleName("backBtn");
    homeBtn.getAccessibleContext().setAccessibleName("homeBtn");

    javax.swing.GroupLayout appsPanelLayout = new javax.swing.GroupLayout(appsPanel);
    appsPanel.setLayout(appsPanelLayout);
    appsPanelLayout.setHorizontalGroup(
      appsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(appsPanelLayout.createSequentialGroup()
        .addComponent(callApp, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(12, 12, 12)
        .addComponent(messagesApp, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(contactsApp, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(facebookApp, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
      .addGroup(appsPanelLayout.createSequentialGroup()
        .addGap(92, 92, 92)
        .addComponent(galleryApp, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(cameraApp, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
      .addComponent(operationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
      .addComponent(bottomAppsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    appsPanelLayout.setVerticalGroup(
      appsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(appsPanelLayout.createSequentialGroup()
        .addGap(6, 6, 6)
        .addGroup(appsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(callApp, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(messagesApp, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(contactsApp, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(facebookApp, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(appsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(cameraApp, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(galleryApp, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
        .addComponent(bottomAppsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(operationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );

    homeTime.setBackground(new java.awt.Color(204, 255, 255));
    homeTime.setFont(new java.awt.Font("Comic Sans MS", 0, 60)); // NOI18N
    homeTime.setForeground(new java.awt.Color(255, 255, 255));
    homeTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    homeTime.setText("00:00 AM");
    homeTime.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

    displayName.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
    displayName.setForeground(new java.awt.Color(255, 255, 255));
    displayName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    displayName.setText("Unknown");
    displayName.setToolTipText("");
    displayName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    displayName.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
              .addContainerGap()
              .addComponent(appsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
              .addGap(27, 27, 27)
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(homeGoogle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(homeTime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))))
          .addGroup(layout.createSequentialGroup()
            .addGap(122, 122, 122)
            .addComponent(displayName, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(30, 30, 30)
        .addComponent(displayName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(homeTime, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(homeGoogle, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(appsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    homeGoogle.getAccessibleContext().setAccessibleName("googleSearch");
    homeTime.getAccessibleContext().setAccessibleName("homeTime");
    displayName.getAccessibleContext().setAccessibleName("displayName");

    getAccessibleContext().setAccessibleName("HomeScreen");
  }// </editor-fold>//GEN-END:initComponents


  private void appActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appActionPerformed
    apps.openApp(evt.getActionCommand());
  }//GEN-LAST:event_appActionPerformed
  
  private void shutdownBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shutdownBtnActionPerformed
    java.awt.Container container = android_parent.getFrame().getContentPane();
    new javax.swing.Timer(100, new java.awt.event.ActionListener() {
      private int counter = 0;
      @Override
      public void actionPerformed(java.awt.event.ActionEvent e) {
        counter++;
        switch(counter) {
          case 1:
            apps.closeAllApps();
            ((java.awt.CardLayout)container.getLayout()).next(container);
            System.out.println("Turning Off Android...");
            break;
          case 23:
            ((javax.swing.Timer)e.getSource()).stop();
            ((java.awt.CardLayout)container.getLayout()).next(container);
            break;
        }
      }
    }).start();
  }//GEN-LAST:event_shutdownBtnActionPerformed

  private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
    apps.closeRecentApp();
  }//GEN-LAST:event_backBtnActionPerformed

  private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
    apps.closeAllApps();
  }//GEN-LAST:event_homeBtnActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private final javax.swing.JLabel displayName = new javax.swing.JLabel();
  private final javax.swing.JLabel homeTime = new javax.swing.JLabel();
  private final javax.swing.JButton topBattery = new javax.swing.JButton();
  private final javax.swing.JLabel topTime = new javax.swing.JLabel();
  // End of variables declaration//GEN-END:variables


}
