
package cellphoneguiapp.njc.Apps;

/**
 *
 * @author Neil Jason Canete
 */
public class Camera extends javax.swing.JPanel {

  /**
   * Creates new form Camera
   */
  public Camera() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    final javax.swing.JLabel camera_content = new javax.swing.JLabel();

    setLayout(new java.awt.CardLayout());

    camera_content.setBackground(new java.awt.Color(0, 0, 0));
    camera_content.setForeground(new java.awt.Color(255, 255, 255));
    camera_content.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    camera_content.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cellphoneguiapp/njc/resources/camera_screen.jpg"))); // NOI18N
    camera_content.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    add(camera_content, "card2");
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
}
