
package cellphoneguiapp.njc.Apps;

/**
 *
 * @author Neil Jason Canete
 */
public class Contacts extends javax.swing.JPanel {

  /**
   * Creates new form Contacts
   */
  public Contacts() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    final javax.swing.JLabel contacts_content = new javax.swing.JLabel();

    setLayout(new java.awt.CardLayout());

    contacts_content.setBackground(new java.awt.Color(0, 0, 0));
    contacts_content.setForeground(new java.awt.Color(255, 255, 255));
    contacts_content.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    contacts_content.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cellphoneguiapp/njc/resources/contact_screen.jpg"))); // NOI18N
    add(contacts_content, "card2");
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
}
