/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package cellphoneguiapp.njc.Apps;

/**
 *
 * @author canet
 */
public class Facebook extends javax.swing.JPanel {

  /**
   * Creates new form Facebook
   */
  public Facebook() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    facebookContent = new javax.swing.JLabel();

    setBackground(new java.awt.Color(0, 0, 0));

    facebookContent.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    facebookContent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cellphoneguiapp/njc/resources/facebook_content.png"))); // NOI18N
    facebookContent.setToolTipText("");
    facebookContent.setVerticalAlignment(javax.swing.SwingConstants.TOP);
    facebookContent.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
    facebookContent.setIconTextGap(0);
    facebookContent.setMaximumSize(new java.awt.Dimension(410, 750));
    facebookContent.setMinimumSize(new java.awt.Dimension(410, 750));
    facebookContent.setPreferredSize(new java.awt.Dimension(410, 750));
    facebookContent.setRequestFocusEnabled(false);
    facebookContent.setVerifyInputWhenFocusTarget(false);
    facebookContent.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(facebookContent, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(facebookContent, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
    );

    facebookContent.getAccessibleContext().setAccessibleName("facebookContent");
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel facebookContent;
  // End of variables declaration//GEN-END:variables
}
