
package cellphoneguiapp.njc.Apps;

/**
 *
 * @author Neil Jason Canete
 */
public class Gallery extends javax.swing.JPanel {

  /**
   * Creates new form Gallery
   */
  public Gallery() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    final javax.swing.JLabel gallery_content = new javax.swing.JLabel();

    gallery_content.setBackground(new java.awt.Color(0, 0, 0));
    gallery_content.setForeground(new java.awt.Color(255, 255, 255));
    gallery_content.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    gallery_content.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cellphoneguiapp/njc/resources/gallery_screen.jpg"))); // NOI18N
    gallery_content.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    gallery_content.setIconTextGap(0);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(gallery_content)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(gallery_content)
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
}
