
package cellphoneguiapp.njc.Apps;

/**
 *
 * @author Neil Jason Canete
 */
public class MessageContent extends javax.swing.JPanel {
  
  private final String senderMsg;
  private final String myMsg;
  private final String msgdate;
  /**
   * Creates new form MessageContent
   * @param msg
   * @param date
   * @param isSender
   */
  public MessageContent(String msg, String date, boolean isSender) {
    senderMsg = isSender ? msg : "";
    myMsg = isSender ? "" : msg;
    msgdate = date;
    initComponents();
    if (!isSender) {
      my_panel.setBackground(new java.awt.Color((int) (Math.random() * 100), (int) (Math.random() * 100), (int) (Math.random() * 100)));
      ((java.awt.CardLayout)getLayout()).next(this);
    } else {
      sender_panel.setBackground(new java.awt.Color((int) (Math.random() * 100), (int) (Math.random() * 100), (int) (Math.random() * 100)));
    }
  }
  
  public String getSenderMsg() {
    return senderMsg;
  }
  
  public String getMyMsg() {
    return myMsg;
  }
  
  public String getDateOfMsg() {
    return msgdate;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    sender_panel = new javax.swing.JPanel();
    final javax.swing.JScrollPane sender_message = new javax.swing.JScrollPane();
    sender_text = new javax.swing.JTextArea();
    final javax.swing.JLabel person_logo_sender = new javax.swing.JLabel();
    my_panel = new javax.swing.JPanel();
    final javax.swing.JScrollPane my_message = new javax.swing.JScrollPane();
    my_text = new javax.swing.JTextArea();
    final javax.swing.JLabel person_logo_my = new javax.swing.JLabel();

    setBackground(new java.awt.Color(25, 25, 25));
    setForeground(new java.awt.Color(255, 255, 255));
    setPreferredSize(new java.awt.Dimension(374, 129));
    setLayout(new java.awt.CardLayout());

    sender_panel.setBackground(new java.awt.Color(25, 25, 25));
    sender_panel.setPreferredSize(new java.awt.Dimension(374, 129));

    sender_message.setBackground(new java.awt.Color(25, 25, 25));
    sender_message.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
    sender_message.setForeground(new java.awt.Color(255, 255, 255));
    sender_message.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
    sender_message.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
    sender_message.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

    sender_text.setEditable(false);
    sender_text.setBackground(new java.awt.Color(25, 25, 25));
    sender_text.setColumns(20);
    sender_text.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
    sender_text.setForeground(new java.awt.Color(255, 255, 255));
    sender_text.setLineWrap(true);
    sender_text.setRows(3);
    sender_text.setTabSize(2);
    sender_text.setText(getSenderMsg());
    sender_text.setToolTipText("");
    sender_text.setBorder(null);
    sender_text.setCaretColor(new java.awt.Color(0, 0, 0));
    sender_text.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
    sender_text.setHighlighter(null);
    sender_message.setViewportView(sender_text);

    person_logo_sender.setBackground(new java.awt.Color(0, 0, 0));
    person_logo_sender.setForeground(new java.awt.Color(255, 255, 255));
    person_logo_sender.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    person_logo_sender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cellphoneguiapp/njc/resources/person_32x32.png"))); // NOI18N
    person_logo_sender.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

    sender_date.setBackground(new java.awt.Color(0, 0, 0));
    sender_date.setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
    sender_date.setForeground(new java.awt.Color(200, 200, 200));
    sender_date.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    sender_date.setText(getDateOfMsg());
    sender_date.setVerticalAlignment(javax.swing.SwingConstants.TOP);
    sender_date.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
    sender_date.setMaximumSize(new java.awt.Dimension(100, 14));
    sender_date.setName(""); // NOI18N
    sender_date.setPreferredSize(new java.awt.Dimension(100, 14));
    sender_date.setRequestFocusEnabled(false);
    sender_date.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

    javax.swing.GroupLayout sender_panelLayout = new javax.swing.GroupLayout(sender_panel);
    sender_panel.setLayout(sender_panelLayout);
    sender_panelLayout.setHorizontalGroup(
      sender_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(sender_panelLayout.createSequentialGroup()
        .addGap(3, 3, 3)
        .addGroup(sender_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(sender_date, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(sender_panelLayout.createSequentialGroup()
            .addComponent(person_logo_sender, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(4, 4, 4)
            .addComponent(sender_message, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGap(32, 32, 32))
    );
    sender_panelLayout.setVerticalGroup(
      sender_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(sender_panelLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(sender_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(person_logo_sender, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(sender_message, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(sender_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    sender_date.getAccessibleContext().setAccessibleName("sender_date");

    add(sender_panel, "sender_page");

    my_panel.setBackground(new java.awt.Color(25, 25, 25));
    my_panel.setForeground(new java.awt.Color(255, 255, 255));
    my_panel.setPreferredSize(new java.awt.Dimension(374, 129));

    my_message.setBackground(new java.awt.Color(25, 25, 25));
    my_message.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
    my_message.setForeground(new java.awt.Color(255, 255, 255));
    my_message.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
    my_message.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
    my_message.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

    my_text.setEditable(false);
    my_text.setBackground(new java.awt.Color(25, 25, 25));
    my_text.setColumns(20);
    my_text.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
    my_text.setForeground(new java.awt.Color(255, 255, 255));
    my_text.setLineWrap(true);
    my_text.setRows(3);
    my_text.setTabSize(2);
    my_text.setText(getMyMsg());
    my_text.setToolTipText("");
    my_text.setBorder(null);
    my_text.setCaretColor(new java.awt.Color(0, 0, 0));
    my_text.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
    my_text.setHighlighter(null);
    my_message.setViewportView(my_text);

    person_logo_my.setBackground(new java.awt.Color(0, 0, 0));
    person_logo_my.setForeground(new java.awt.Color(255, 255, 255));
    person_logo_my.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    person_logo_my.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cellphoneguiapp/njc/resources/person_yellow_32x32.png"))); // NOI18N
    person_logo_my.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

    my_date.setBackground(new java.awt.Color(0, 0, 0));
    my_date.setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
    my_date.setForeground(new java.awt.Color(200, 200, 200));
    my_date.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    my_date.setText(getDateOfMsg());
    my_date.setVerticalAlignment(javax.swing.SwingConstants.TOP);
    my_date.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
    my_date.setMaximumSize(new java.awt.Dimension(100, 14));
    my_date.setName(""); // NOI18N
    my_date.setPreferredSize(new java.awt.Dimension(100, 14));
    my_date.setRequestFocusEnabled(false);
    my_date.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

    javax.swing.GroupLayout my_panelLayout = new javax.swing.GroupLayout(my_panel);
    my_panel.setLayout(my_panelLayout);
    my_panelLayout.setHorizontalGroup(
      my_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(my_panelLayout.createSequentialGroup()
        .addGap(22, 22, 22)
        .addGroup(my_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(my_date, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(my_panelLayout.createSequentialGroup()
            .addComponent(my_message, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(2, 2, 2)
            .addComponent(person_logo_my, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    my_panelLayout.setVerticalGroup(
      my_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(my_panelLayout.createSequentialGroup()
        .addGap(11, 11, 11)
        .addGroup(my_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(person_logo_my, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(my_message, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(6, 6, 6)
        .addComponent(my_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    add(my_panel, "sender_page");
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private final javax.swing.JLabel my_date = new javax.swing.JLabel();
  private javax.swing.JPanel my_panel;
  private javax.swing.JTextArea my_text;
  private final javax.swing.JLabel sender_date = new javax.swing.JLabel();
  private javax.swing.JPanel sender_panel;
  private javax.swing.JTextArea sender_text;
  // End of variables declaration//GEN-END:variables
}
