
package cellphoneguiapp.njc.Apps;


/**
 *
 * @author Neil Jason Canete
 */
public class MessagesListContent extends javax.swing.JPanel {
  
  private final int sender_id;
  private final String sender_name;
  private final String sender_number;
  private java.awt.event.ActionListener listener;
  
  /**
   * Creates new form MessagesListContent
   * @param sender_id
   * @param number
   * @param sender_name
   */
  public MessagesListContent(int sender_id, String number, String sender_name) {
    this.sender_id = sender_id;
    this.sender_number = number;
    this.sender_name = sender_name;
    initComponents();
  }

  public Integer getSenderId() {
    return this.sender_id;
  }
  
  public String getSenderName() {
    return sender_name;
  }
  
  public String getSenderNumber() {
    return sender_number;
  }
  
  public String getDisplayName() {
    return getSenderName() + " (" + getSenderNumber() + ")";
  }
  
  public void setButtonAction(java.awt.event.ActionListener listener) {
    this.listener = listener;
  }
  
  public javax.swing.JButton getButton() {
    return senderButton;
  }
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    setBackground(new java.awt.Color(0, 0, 0));
    setMaximumSize(new java.awt.Dimension(390, 95));
    setPreferredSize(new java.awt.Dimension(390, 95));

    senderButton.setBackground(new java.awt.Color(25, 25, 25));
    senderButton.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
    senderButton.setForeground(new java.awt.Color(255, 255, 255));
    senderButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cellphoneguiapp/njc/resources/messagePersonIcon.png"))); // NOI18N
    senderButton.setText(getDisplayName());
    senderButton.setActionCommand("");
    senderButton.setBorderPainted(false);
    senderButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    senderButton.setDefaultCapable(false);
    senderButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    senderButton.setIconTextGap(16);
    senderButton.setLabel(getDisplayName());
    senderButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
    senderButton.setMaximumSize(new java.awt.Dimension(400, 85));
    senderButton.setMinimumSize(new java.awt.Dimension(400, 85));
    senderButton.setPreferredSize(new java.awt.Dimension(400, 85));
    senderButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        senderButtonActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(senderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 390, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addGap(5, 5, 5)
        .addComponent(senderButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(5, 5, 5))
    );

    senderButton.getAccessibleContext().setAccessibleName("");
  }// </editor-fold>//GEN-END:initComponents

  private void senderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senderButtonActionPerformed
    if (listener != null) {
      evt.setSource(this);
      listener.actionPerformed(evt);
    }
  }//GEN-LAST:event_senderButtonActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private final javax.swing.JButton senderButton = new javax.swing.JButton();
  // End of variables declaration//GEN-END:variables

}
